
#workflow's name
name: Check Python script

#trigger workflow when pushed in main branch
on:
  push:
    branches: [ master ]

  schedule:
    - cron: '0 8 * * *' #minute hour day_of_month day_of_week 

#define the list  of jobs (can be multiple)
jobs:
  run-script: #name of the 1st job

#run on the latest version of Ubuntu (VM)
    runs-on: ubuntu-latest

#List of steps to run in order
    steps:

#Download the content of the Repo
    - name: Checkout repository
      uses: actions/checkout@v3 #@v3 = version 3 of the checkout action (to be sure it works)

#Set up Python on VM
    - name: Set up Python
      uses: actions/setup-python@v4
#define the version of Python
      with:
        python-version: '3.10'

#install library/dependencies needed for the script
    - name: Install dependencies
      run: |
        pip install requests

#Run the Python Script
    - name: Run the script
      run: |
        python3 script.py
#upload log.txt as an artifact
    - name : Upload log file
      uses: actions/upload-artifact@v4
      with:
        name: site-checker-log
        path: log.txt

    - name: Create git tag
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag auto-log-${{ github.run_number }}
        git push origin auto-log-${{ github.run_number }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "auto-log-${{ github.run_number }}"
        name: "Automated Log #${{ github.run_number }}"
        body: "Log file from workflow run #${{ github.run_id }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Upload log.txt to release
      uses: softprops/action-gh-release@v1
      with:
        files: log.txt
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
