name: Create GH release

on:
    push:
        branches: [master]
            

jobs:
    tag:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name : checkout code
              uses: actions/checkout@v4

            - name: Current Date
              id: date
              run: echo "TAG=v$(date + '%Y.%m.%d. %H%M%S')">>$GITHUB_ENV

            - name: Create Tag
              run: |
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git tag $TAG
                git push origin $TAG